num_show_pigs = 5000
num_pigs_per_fence = 10000
min_mean_to_median = 2
max_mean_to_median = 12
pmb_rtp = 0.96
simulation_trials = 5000
test_spins = [ 50, 100, 200,]
test_spins_weights = [ 0.3, 0.4, 0.3,]
score_type = "rtp"
max_trial_dist = 15
game_name = "0_0_scatter"
path_to_games = "../games/"
run_1000_batch = false
bet_type = "base"
threads_for_fence_construction = 4
threads_for_show_construction = 4
